apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: whoami
  namespace: demo
spec:
  minReplicas: 2
  maxReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: whoami
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
